### ISSUE TITLE
Translation problem - events not displayed

### ISSUE THREAD

**Issue by devxpoint** [lochmueller/calendarize#315]
Hi,
I have a simple list view with events in default language (German).
Site configuration:

```
languages:
  -
    title: Deutsch
    enabled: true
    languageId: '0'
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ltr
    flag: de
  -
    title: English
    enabled: true
    languageId: '1'
    base: /en/
    typo3Language: en
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-US
    direction: ''
    fallbackType: script
    flag: gb
  -
```

Then translated as usual the pages and its contents...
But when I switch to English in FE, the plugin says: 
"There are no events in the current view."

Bug or misconfiguration?
Other pages are showing English content...

TYPO3 9.5.9
calendarize 4.1.3
