### ISSUE TITLE
Add UrlRewrite configuration in documentation for TYPO3 > 9.0

### ISSUE THREAD

**Issue by lochmueller** [lochmueller/calendarize#327]
Example:
```
Calendarize:
    type: Extbase
    extension: Calendarize
    plugin: Calendar
    routes:
      - { routePath: '/seite{page}', _controller: 'Calendar::list', _arguments: {'page': '@widget_0/currentPage'} }
      - { routePath: '/termin{index-title}', _controller: 'Calendar::detail', _arguments: {'index-title': 'index'} }
      - { routePath: '/woche{cal-week}{cal-year}', _controller: 'Calendar::week', _arguments: {'cal-week': 'week', 'cal-year': 'year'} }
      - { routePath: '/monat{cal-month}{cal-year}', _controller: 'Calendar::month', _arguments: {'cal-month': 'month', 'cal-year': 'year'} }
      - { routePath: '/tag{cal-day}{cal-month}{cal-year}', _controller: 'Calendar::month', _arguments: {'cal-day': 'day','cal-month': 'month', 'cal-year': 'year'} }
    defaultController: 'Calendar::list'
    defaults:
      page: '0'
    aspects:
      page:
        type: StaticRangeMapper
        start: '1'
        end: '100'
      cal-day:
        type: StaticRangeMapper
        start: '1'
        end: '31'
      cal-week:
        type: StaticRangeMapper
        start: '1'
        end: '65'
      cal-month:
        type: StaticRangeMapper
        start: '1'
        end: '12'
      cal-year:
        type: StaticRangeMapper
        start: '2000'
        end: '2030'
```
