### ISSUE TITLE
URL Handling of year view doesn't work

### ISSUE THREAD

**Issue by TFaehrmann** [lochmueller/calendarize#376]
Tried to add a route definition for the year action, but it doesn't work.

```yaml
  CalendarizePlugin:
    type: Extbase
    extension: Calendarize
    plugin: Calendar
    routes:
      - { routePath: '/{cal-year}', _controller: 'Calendar::year', _arguments: {'cal-year': 'year'} }
    aspects:
      cal-year:
        type: StaticRangeMapper
        start: '2000'
        end: '2030'
```

Also there is only a description for the detail view at the documentation.
