### ISSUE TITLE
Using ICS download with routeEnhancer - hmac-validation not executed

### ISSUE THREAD

**Issue by albig** [lochmueller/calendarize#710]
I would like to make more speaking URLs for ICS/ICal downloads. With the following RouteEnhancer the URL looks like

https://example.com/ics/123456789.ics?cHash=987654321

hmac = 123456789
cHash = 987654321

```
routeEnhancers:
  Calendarize:
    type: Extbase
    extension: Calendarize
    plugin: Calendar
    routes:
     - routePath: '/ics/{hmac}.{format}'
       _controller: 'Calendar::list'
    defaultController: 'Calendar::list'
    aspects:
      format:
        type: StaticValueMapper
        map:
          'ics': 'ics'
```

With an simple aspect mapper like explained here: https://stackoverflow.com/questions/53053093/how-do-i-write-a-routing-aspect-mapper-for-typo3-9-lts

I get URLs without cHash.

https://example.com/ics/123456789.ics

Now the funny part. The hmac is _not_ validated at all. I could write just https://example.com/ics/somestring.ics

Am I wrong or is just the line https://github.com/lochmueller/calendarize/blob/master/Classes/Controller/AbstractCompatibilityController.php#L96
wrong? 
`sendHeaderAndFilename()` sends already the ICS-calendar and ends the HTTP requests. The following hmac-validation is never executed.

If this is a bug, I'll provide a PR of course. I'm just not sure ;-)
