### ISSUE TITLE
RouteEnhancer: Two events with same title and on same day

### ISSUE THREAD

**Issue by DavidBruchmann** [lochmueller/calendarize#762]
How to map two events on the same day when the title is the same too?
Imagine a cinema where a movie is shown 3 times a day.

I tried to add some more details like below, it's not working though

```

    routes:
      -
        routePath: '/{calendarize_event_label}/{index}/{hour}/{minute}'
        _controller: 'Calendar::detail'
...
    aspects:
   ...
   
      hour:
        type: StaticRangeMapper
        start: '0'
        end: '24'
      minute:
        type: StaticRangeMapper
        start: '0'
        end: '60'

    ....

      calendarize_hour_label:
        type: LocaleModifier
        default: hour
        localeMap:
          -
            locale: 'de_.*'
            value: stunde
      calendarize_minute_label:
        type: LocaleModifier
        default: minute
        localeMap:
          -
            locale: 'de_.*'
            value: minute
```

**Comment by lochmueller** [comment]
Hey @DavidBruchmann 

Which EXT:calendarize version do you use? In the current version for TYPO3 v11 is already a handling, that the slug information is part of the index table and use collision detection. So this should not a problem anymore. Please check your DB. Could you confirm, that the tx_clanendarize_domain_model_index (not the event!!!) table has two entries with the same „slug“ value?

Related Issue: https://github.com/lochmueller/calendarize/issues/540

Regards,
Tim

**Comment by DavidBruchmann** [comment]
Thanks for the response, are you sure that the yaml in main is including the feature?

Concerning the entries in tx_clanendarize_domain_model_index:  
Yes, slugs of same events get a count appended in the form `-n` with n as integer.  
Instead of this integer I'd like to have the date in form H:i, but the `-` as separator is good.

my versions currently:  
calendarize: 12.4.4  
TYPO3 11.5.21

**Comment by okmiim** [comment]
Hi @DavidBruchmann,

in your SitePackage you could add a event listener to modify the slug during generation.
The event listener could look something like this:

_AddEventTimeSlugListener.php_
```php
<?php

declare(strict_types=1);

namespace MyVendor\MyExtension\EventListener;

use HDNET\Calendarize\Event\SlugSuffixGenerationEvent;

final class AddEventTimeSlugListener
{
    public function __invoke(SlugSuffixGenerationEvent $event): void
    {
        // Optional: some additional checks, e.g. based on Model or page id (pid)
        // Get the start_time as seconds since day start
        $startTime = $event->getRecord()['start_time'];
        // Add to the existing slug (e.g. test-20201103) the current time (17-15) resulting in test-20201103-1715
        $newSlug = $event->getSlug() . '-' . date('Hi', $startTime);
        // Update the slug
        $event->setSlug($newSlug);
    }
}

```

_Services.yaml_
```yaml
...
  MyVendor\MyExtension\EventListener\AddEventTimeSlugListener:
    tags:
      - name: event.listener
        identifier: 'addEventTimeSlug'
        event: HDNET\Calendarize\Event\SlugSuffixGenerationEvent
```

Note: if the slug is still not unique, the counting suffix will be added at later stage

See [Listen to an event (TYPO3)](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/HowTo/Events/Index.html#listen-to-an-event) for general implementation details.

- [ ] Add example to documentation @okmiim
- [ ] Add baseSlug and SlugHelper to SlugSuffixGenerationEvent for better convenience @okmiim
